// Code generated by ent, DO NOT EDIT.

package song

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the song type in the database.
	Label = "song"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldFilename holds the string denoting the filename field in the database.
	FieldFilename = "filename"
	// FieldGenre holds the string denoting the genre field in the database.
	FieldGenre = "genre"
	// FieldCopyright holds the string denoting the copyright field in the database.
	FieldCopyright = "copyright"
	// FieldTocinfo holds the string denoting the tocinfo field in the database.
	FieldTocinfo = "tocinfo"
	// EdgeProjectSongs holds the string denoting the project_songs edge name in mutations.
	EdgeProjectSongs = "project_songs"
	// Table holds the table name of the song in the database.
	Table = "songs"
	// ProjectSongsTable is the table that holds the project_songs relation/edge.
	ProjectSongsTable = "project_songs"
	// ProjectSongsInverseTable is the table name for the ProjectSong entity.
	// It exists in this package in order to avoid circular dependency with the "projectsong" package.
	ProjectSongsInverseTable = "project_songs"
	// ProjectSongsColumn is the table column denoting the project_songs relation/edge.
	ProjectSongsColumn = "song_id"
)

// Columns holds all SQL columns for song fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldFilename,
	FieldGenre,
	FieldCopyright,
	FieldTocinfo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// FilenameValidator is a validator for the "filename" field. It is called by the builders before save.
	FilenameValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the Song queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByFilename orders the results by the filename field.
func ByFilename(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFilename, opts...).ToFunc()
}

// ByGenre orders the results by the genre field.
func ByGenre(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGenre, opts...).ToFunc()
}

// ByCopyright orders the results by the copyright field.
func ByCopyright(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCopyright, opts...).ToFunc()
}

// ByTocinfo orders the results by the tocinfo field.
func ByTocinfo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTocinfo, opts...).ToFunc()
}

// ByProjectSongsCount orders the results by project_songs count.
func ByProjectSongsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProjectSongsStep(), opts...)
	}
}

// ByProjectSongs orders the results by project_songs terms.
func ByProjectSongs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectSongsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProjectSongsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectSongsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ProjectSongsTable, ProjectSongsColumn),
	)
}
