// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// ProjectSong is the predicate function for projectsong builders.
type ProjectSong func(*sql.Selector)

// Song is the predicate function for song builders.
type Song func(*sql.Selector)
